
export interface Point {
  x: number;
  y: number;
}

export interface GeneratedImage {
  id: string;
  url: string; // Base64 data URL
  prompt: string;
  timestamp: number;
  params: GenerationParams;
  usedPoint: Point; // The specific point used for this image
  embedding?: number[]; // Semantic embedding of the prompt
}

export enum ModelOption {
  FLASH = "gemini-2.5-flash-image",
  PRO = "gemini-3.1-flash-image-preview"
}

export enum ColorPalette {
  NONE = "Default",
  VIBRANT = "Vibrant",
  PASTEL = "Pastel",
  MONOCHROME = "Monochrome",
  SEPIA = "Sepia",
  CYBER_NEON = "Cyber Neon",
  EARTH_TONES = "Earth Tones",
  COOL_BLUES = "Cool Blues",
  WARM_SUNSET = "Warm Sunset"
}

export enum AspectRatio {
  SQUARE = "1:1",
  LANDSCAPE = "16:9",
  PORTRAIT = "9:16",
  WIDE = "3:4", // Technically tall, but 3:4 / 4:3 are standard
  CLASSIC = "4:3"
}

export enum Lighting {
  NONE = "Default",
  GOLDEN_HOUR = "Golden Hour",
  CINEMATIC = "Cinematic Studio",
  DRAMATIC = "Dramatic/High Contrast",
  NATURAL = "Soft Natural Light",
  NEON = "Neon Rim Lights",
  BIOLUMINESCENT = "Bioluminescent Glow",
  FOGGY = "Moody Foggy",
  STUDIO = "Professional Studio"
}

export enum DepthOfField {
  NONE = "Default",
  SHALLOW = "Shallow (Bokeh/Blurry BG)",
  DEEP = "Deep (Everything in Focus)"
}

export interface GenerationParams {
  prompt: string;
  imageCount: number;
  seed: number;
  useCustomSeed: boolean;
  seedAngle: number; // Used to persist the visual state of the dial
  styleA: string;
  styleB: string;
  matrixPoints: Point[]; 
  negativePrompts: string[];
  uploadedImage?: string; 
  model: ModelOption; 
  colorPalette: ColorPalette;
  colorCount: number; // 0 = Unlimited
  aspectRatio: AspectRatio;
  lighting: Lighting;
  depthOfField: DepthOfField;
}

export enum StyleOption {
  NONE = "None",
  CYBERPUNK = "Cyberpunk",
  WATERCOLOR = "Watercolor",
  REALISTIC = "Photorealistic",
  SKETCH = "Pencil Sketch",
  RETRO = "Retro 80s",
  SURREAL = "Surrealism",
  PIXEL = "Pixel Art",
  PIXEL_GAME_ASSET = "2D Pixel Game Asset",
  VECTOR_ART = "Vector Art (Solid BG)",
  VECTOR_LAYERS = "Vector Layers (for Editing)",
  IMPRESSIONIST = "Impressionist",
  NOIR = "Film Noir",
  ANIME = "Anime",
  OIL_PAINTING = "Oil Painting",
  CLAY = "Claymation",
  HOLOGRAPHIC = "Holographic",
  RUBBER_HOSE = "Rubber Hose Cartoon",
  STEAMPUNK = "Steampunk",
  VAPORWAVE = "Vaporwave",
  UKIYOE = "Ukiyo-e Woodblock",
  LOW_POLY = "Low Poly 3D",
  GOTHIC = "Gothic Fantasy",
  POP_ART = "Pop Art",
  BAUHAUS = "Bauhaus Design",
  ART_NOUVEAU = "Art Nouveau",
  ISOMETRIC = "Isometric 3D",
  RENAISSANCE = "Renaissance Painting",
  GLITCH = "Glitch Art",
  PAPERCRAFT = "Papercraft Layered",
  GRAFFITI = "Street Art Graffiti",
  STAINED_GLASS = "Stained Glass",
  SESAME = "Sesame Street Puppet",
  // New Styles
  DIORAMA = "Museum Diorama",
  MINIATURE = "Wargaming Miniature",
  COLLAGE = "Photo Collage",
  MOSAIC = "Organic Mosaic",
  TIE_DYE = "Tie Dye",
  POINTILLISM = "Pointillism",
  PS1 = "PS1 Graphics",
  GUNPLA = "Gunpla Model",
  KAWAII = "Kawaii",
  TOULOUSE = "Toulouse-Lautrec",
  
  MINIMALIST = "Minimalist",
  CINEMATIC = "Cinematic",
  VINTAGE = "Vintage",
  THREE_D_RENDER = "3D Render",
  ABSTRACT = "Abstract",
  LINE_ART = "Line Art",
  VECTOR_DESIGN = "Vector Design",
  NEO_NOIR = "Neo-noir",
  ART_DECO = "Art Deco",
  CUBISM = "Cubism",
  EXPRESSIONISM = "Expressionism",
  FAUVISM = "Fauvism",
  FUTURISM = "Futurism",
  BAROQUE = "Baroque",
  ROCOCO = "Rococo",
  CONSTRUCTIVISM = "Constructivism",
  POST_IMPRESSIONISM = "Post-Impressionism",
  ROMANTICISM = "Romanticism",
  REALISM = "Realism",
  BRUTALISM = "Brutalism",
  DADA_ISM = "Dadaism",
  SYMBOLISM = "Symbolism",
  MANNERISM = "Mannerism",
  PRECISIONISM = "Precisionism",
  WESTERN = "Western",
  NINJA = "Ninja",
  SAMURAI = "Samurai",
  PIRATE = "Pirate",
  VIKING = "Viking",
  KNIGHT = "Knight",
  MECHA = "Mecha",
  KAIJU = "Kaiju",
  ZOMBIE = "Zombie",
  RETRO_FUTURISM = "Retro-futurism",
  POST_APOCALYPTIC = "Post-apocalyptic",
  DIESELPUNK = "Dieselpunk",
  SOLARPUNK = "Solarpunk",
  SPACE_OPERA = "Space opera",
  COSMIC_HORROR = "Cosmic horror",
  FAIRYTALE = "Fairytale",
  HIGH_FANTASY = "High fantasy",
  CYBERNETIC = "Cybernetic",
  PREHISTORIC = "Prehistoric",
  EIGHT_BIT = "8-bit",
  SIXTEEN_BIT = "16-bit",
  VOXEL = "Voxel",
  CEL_SHADED = "Cel-shaded",
  ARCADECORE = "Arcadecore",
  CHIBI = "Chibi",
  NEXT_GEN = "Next-gen",
  DARK_FANTASY = "Dark fantasy",
  COZY_GAMING = "Cozy gaming",
  RGB_GAMER = "RGB gamer",
  RAY_TRACED = "Ray-traced",
  HIGH_POLY = "High-poly",
  HAND_PAINTED = "Hand-painted",
  FLAT_VECTOR = "Flat vector",
  MONOCHROMATIC = "Monochromatic",
  ASCII_ART = "ASCII art",
  PC_98 = "PC-98",
  SYNTHWAVE = "Synthwave",
  COTTAGECORE = "Cottagecore",
  DARK_ACADEMIA = "Dark Academia",
  LIGHT_ACADEMIA = "Light Academia",
  Y2K = "Y2K",
  FRUTIGER_AERO = "Frutiger Aero",
  WEIRDCORE = "Weirdcore",
  DREAMCORE = "Dreamcore",
  LIMINAL_SPACE = "Liminal space",
  GOBLINCORE = "Goblincore",
  CLUTTERCORE = "Cluttercore",
  MAXIMALISM = "Maximalism",
  WHIMSIGOTH = "Whimsigoth",
  COQUETTE = "Coquette",
  KIDCORE = "Kidcore",
  INDIE_SLEAZE = "Indie sleaze",
  GORPCORE = "Gorpcore",
  NORMCORE = "Normcore",
  GLITCHCORE = "Glitchcore",
  WES_ANDERSON = "Wes Anderson",
  KUBRICKIAN = "Kubrickian",
  LYNCHIAN = "Lynchian",
  BURTONESQUE = "Burtonesque",
  GRINDHOUSE = "Grindhouse",
  GIALLO = "Giallo",
  TECHNICOLOR = "Technicolor",
  ART_HOUSE = "Art house",
  CLASSIC_HOLLYWOOD = "Classic Hollywood",
  FOUND_FOOTAGE = "Found footage",
  CINEMA_VERITE = "Cinema verite",
  TECH_NOIR = "Tech-noir",
  SPAGHETTI_WESTERN = "Spaghetti Western",
  SLASHER = "Slasher",
  STOP_MOTION_FILM = "Stop-motion Film",
  TARANTINO = "Tarantino",
  A24 = "A24",
  MOCKUMENTARY = "Mockumentary",
  NEO_REALISM = "Neo-realism",
  BLAXPLOITATION = "Blaxploitation",
  CEREAL_BOX = "Cereal box",
  POLAROID_FRAME = "Polaroid frame",
  MAGAZINE_COVER = "Magazine cover",
  TRADING_CARD = "Trading card",
  COMIC_PANEL = "Comic panel",
  POSTAGE_STAMP = "Postage stamp",
  MOVIE_POSTER = "Movie poster",
  VINYL_SLEEVE = "Vinyl sleeve",
  VHS_COVER = "VHS cover",
  WANTED_POSTER = "Wanted poster",
  TAROT_CARD = "Tarot card",
  NEWSPAPER_PRINT = "Newspaper print",
  POSTCARD_BORDER = "Postcard border",
  BLISTER_PACK = "Blister pack",
  PASSPORT_PHOTO = "Passport photo",
  VIEW_MASTER = "View-Master",
  BILLBOARD = "Billboard",
  BOOK_JACKET = "Book jacket",
  WINE_LABEL = "Wine label",
  ARCADE_CABINET = "Arcade cabinet",
  MATTE = "Matte",
  GLOSSY = "Glossy",
  BRUSHED_METAL = "Brushed metal",
  CRUMPLED_PAPER = "Crumpled paper",
  FROSTED_GLASS = "Frosted glass",
  LIQUID_CHROME = "Liquid chrome",
  GOLD_LEAF = "Gold leaf",
  CARBON_FIBER = "Carbon fiber",
  MARBLE = "Marble",
  CONCRETE = "Concrete",
  WOOD_GRAIN = "Wood grain",
  DISTRESSED_LEATHER = "Distressed leather",
  CRACKED_PAINT = "Cracked paint",
  RUST_PATINA = "Rust patina",
  CANVAS_FABRIC = "Canvas Fabric",
  DENIM = "Denim",
  VELVET = "Velvet",
  TERRAZZO = "Terrazzo",
  STUCCO = "Stucco",
  GRAPHITE = "Graphite",
  COLORED_PENCIL = "Colored pencil",
  CHALK_PASTEL = "Chalk pastel",
  OIL_PASTEL = "Oil pastel",
  ACRYLIC_PAINT = "Acrylic paint",
  GOUACHE = "Gouache",
  TEMPERA = "Tempera",
  INK_WASH = "Ink wash",
  ETCHING = "Etching",
  LINOCUT = "Linocut",
  WOODCUT = "Woodcut",
  SCREENPRINT = "Screenprint",
  LITHOGRAPH = "Lithograph",
  AIRBRUSH = "Airbrush",
  SCRATCHBOARD = "Scratchboard",
  TROMPE_LOEIL = "Trompe-l’œil",
  CHIAROSCURO = "Chiaroscuro",
  HYPERREALISM = "Hyperrealism",
  SUMI_E = "Sumi-e",
  PRE_RAPHAELITE = "Pre-Raphaelite",
  NEOCLASSICISM = "Neoclassicism",
  TENEBRISM = "Tenebrism",
  STIPPLING = "Stippling",
  INTRICATE_FILIGREE = "Intricate filigree",
  KINTSUGI = "Kintsugi",
  CHINOISERIE = "Chinoiserie",
  ILLUMINATED_MANUSCRIPT = "Illuminated manuscript",
  FINE_LINE_ENGRAVING = "Fine-line engraving",
  CLOISONNE = "Cloisonné",
  SFUMATO = "Sfumato",
  GOTHIC_REVIVAL = "Gothic revival",
  ISLAMIC_GEOMETRIC = "Islamic geometric",
  NEURAL_BAROQUE = "Neural Baroque",
  QUANTUM_GLITCH = "Quantum Glitch",
  BIO_SYNTHETIC = "Bio-synthetic",
  ALGORITHMIC_BRUTALISM = "Algorithmic Brutalism",
  PHYGITAL_CRAFT = "Phygital Craft",
  LATENT_SURREALISM = "Latent Surrealism",
  DATA_SCULPTURE = "Data Sculpture",
  CYBER_BIOPHILIA = "Cyber-Biophilia",
  LIQUID_GEOMETRY = "Liquid Geometry",
  HYPER_DIMENSIONAL = "Hyper-Dimensional",
  SPECTRAL_DIGITAL = "Spectral Digital",
  NANO_CHIC = "Nano-Chic",
  PLASMATIC = "Plasmatic",
  NEURO_EXPRESSIONISM = "Neuro-Expressionism",
  CHRONOSTATIC = "Chronostatic",
  VOXEL_FLUID = "Voxel-Fluid",
  META_TEXTURAL = "Meta-Textural",
  ECHOCORE = "Echocore",
  SYNTH_ORGANIC = "Synth-Organic",
  GENERATIVE_GOTHIC = "Generative Gothic",
  BENTO_GRID = "Bento grid",
  SPLIT_SCREEN = "Split-screen",
  ASYMMETRIC = "Asymmetric",
  MODULAR = "Modular",
  WHITESPACE = "Whitespace",
  EDITORIAL_SPREAD = "Editorial spread",
  TRIPTYCH = "Triptych",
  DIPTYCH = "Diptych",
  RADIAL_SYMMETRIC = "Radial symmetry",
  BROKEN_GRID = "Broken grid",
  GOLDEN_RATIO = "Golden ratio",
  HIERARCHICAL = "Hierarchical",
  OVERLAPPING = "Overlapping",
  SWISS_STYLE = "Swiss style",
  CARD_LAYOUT_STYLE = "Card layout",
  COLUMNAR = "Columnar",
  STORYBOARD = "Storyboard",
  MULTIPANEL = "Multipanel",
  Z_PATTERN = "Z-pattern",
  CENTRAL_FOCUS = "Central focus",
  ABSTRACT_EXPRESSIONISM = "Abstract Expressionism",
  OP_ART = "Op Art",
  SUPREMATISM = "Suprematism",
  DE_STIJL = "De Stijl",
  CONCEPTUAL_ART = "Conceptual Art",
  ARTS_AND_CRAFTS = "Arts & Crafts",
  REGIONALISM = "Regionalism",
  HUDSON_RIVER_SCHOOL = "Hudson River School",
  NEO_EXPRESSIONISM = "Neo-Expressionism",
  ARTE_POVERA = "Arte Povera",
  SOCIAL_REALISM = "Social Realism",
  ORPHISM = "Orphism",
  VIENNA_SECESSION = "Vienna Secession",
  LES_NABIS = "Les Nabis",
  ASHCAN_SCHOOL = "Ashcan School",
  FLUXUS = "Fluxus",
  ART_INFORMEL = "Art Informel",
  SYNCHROMISM = "Synchromism",
  SPATIALISM = "Spatialism",
  COLORING_BOOK = "Coloring book",
  ROYAL_PORTRAIT = "Royal portrait",
  STICKER_CUTOUT = "Sticker cutout",
  BRICK_FIGURINE = "Brick figurine",
  TOY_COLLECTIBLE = "Toy collectible",
  EMBROIDERY_PATCH = "Embroidery patch",
  KNITTED_PLUSH = "Knitted plush",
  PAPER_CUTOUT = "Paper cutout",
  NEON_SIGN = "Neon sign",
  CHALKBOARD_SKETCH = "Chalkboard sketch",
  CARICATURE_AVATAR = "Caricature avatar",
  WATERCOLOR_SPLASH = "Watercolor splash",
  COMIC_HALFTONE = "Comic halftone",
  LASER_ENGRAVE = "Laser engrave",
  SAND_ART = "Sand art",
  GLOW_OUTLINE = "Glow outline",
  SCRATCH_ART = "Scratch art",
  VINTAGE_CARTOON = "Vintage cartoon",
  MANGA_AVATAR = "Manga avatar",
  SILHOUETTE_ART = "Silhouette art",
  HOLOGRAPHIC_BILLBOARD = "Holographic billboard",
  RETRO_BILLBOARD = "Retro billboard",
  TIMES_SQUARE = "Times Square",
  NEON_MARQUEE = "Neon marquee",
  BUS_SHELTER = "Bus shelter",
  HEDGE_MAZE = "Hedge maze",
  LABYRINTH_GRID = "Labyrinth grid",
  CIRCUIT_MAZE = "Circuit maze",
  VECTOR_MAZE = "Vector maze",
  PUZZLE_MATRIX = "Puzzle matrix",
  JRPG_RETRO = "JRPG retro",
  SURVIVAL_HORROR = "Survival horror",
  VISUAL_NOVEL = "Visual novel",
  COZY_SIM = "Cozy sim",
  FPS_HUD = "FPS HUD",
  PLATFORMER_LEVEL = "Platformer level",
  FIGHTING_GAME = "Fighting game",
  METROIDVANIA_MAP = "Metroidvania map",
  ROGUE_LIKE = "Rogue-like",
  ARCADE_UI = "Arcade UI",
  DIGIMON_DIGIVOLUTION = "Digimon digivolution"
}

export const NEGATIVE_PROMPTS_OPTIONS = [
  "Blurry",
  "Low Quality",
  "Distorted",
  "Bad Anatomy",
  "Text/Watermark",
  "Oversaturated",
  "Visual Noise/Clutter"
];

declare global {
  interface Window {
    aistudio?: {
      hasSelectedApiKey: () => Promise<boolean>;
      openSelectKey: () => Promise<void>;
    };
  }
}
